### ISSUE TITLE
Remove unused packages.

### ISSUE THREAD

**Issue by berkerdemirer** [NoQuarterTeam/boilerplate-remix#94]
Hey, I was investigating the boilerplate and I realised some of the packages are not used. Maybe it is better to clean them?

**Comment by JClackett** [comment]
Hey! which ones aren't used? I will double check as to why they're in

**Comment by berkerdemirer** [comment]
"eslint-plugin-flowtype": "8.0.3",
    "eslint-plugin-jsx-a11y": "6.5.1",
    "rimraf": "3.0.2",
    "babel-eslint": "10.1.0",

I think these are not used/needed

**Comment by JClackett** [comment]
Pushed an update removing these!
